Pomodoro/Pomodoro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("Pomodoro_App/", include("Pomodoro_App.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pomodoro/Pomodoro_App/urls.py
from django.urls import path

from . import views

app_name = "Pomodoro"
urlpatterns = [
    path("", views.settings, name="settings"),
    path("timer/", views.pomodoro_timer, name="timer"),
    path("clock/",views.wallClock,name="clock"),
    path("delete-task/<int:task_id>/",views.deleteTask,name="task-deletion"),
]

Pomodoro/Pomodoro_App/models.py
from django.db import models

# below validator is imported here becasue PositiveIntegerField is not working.
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.utils import timezone

# Create your models here.
# Creating models based on this website ---> https://pomofocus.io/app
# We created 5 models ---> 5 different tables. 
# 1) Timer
# 2) Tasks
# 3) Sound
# 4) Theme ---> Background theme
# 5) Notification
# 7) Block website

# TODO: Make models more complex once basic website is made.




# connect sound with timer model ----> no need
class Sounds(models.Model):
    sound = models.FileField(upload_to="Audio/uploads/%Y/%m/%d/")
    sound_name = models.CharField(max_length=20)

    def __str__(self):
        return f"Music: {self.sound_name}"

    def get_sounds_url(self):
        # here our 'sound' is FileField attribute thats why we did self.sound.url cause FileField
        # attribute contains the url of the media file.
        return self.sound.url


def get_now_date():
    return timezone.now()

class Timer(models.Model):
    pomodoro = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)])
    short_break = models.PositiveIntegerField(default=0)
    long_break = models.PositiveIntegerField(default=0)
    auto_start_pomodoros = models.BooleanField(default=False)
    auto_start_breaks = models.BooleanField(default=False)
    number_of_interval = models.PositiveIntegerField(default=0)
    published_date = models.DateTimeField(
        "date published",
        default=get_now_date,
    )

    def __str__(self):
        return f"Pomodoro: {self.pomodoro} ---- Short-Break: {self.short_break} and Long-Break: {self.long_break} ---- Total number of interval: {self.number_of_interval}"

    def get_absolute_url(self):
        return reverse("Pomodoro:settings")


# No need to connect Tasks with Timer in a many-to-one relationship. 
# TODO: You need to figure out how to update and delete the task on the timer.html page without reloading the page again each time.
class Tasks(models.Model):
    task = models.CharField(max_length=100,name = "task_text")
    compeleted = models.BooleanField(default = False)
    published_date = models.DateTimeField("date published", default=get_now_date)
    end_time = models.DateTimeField("Time completed",default = get_now_date)

    def __str__(self):
        return f"Task: {self.task_text}"
    
    def endTime(self):
        if self.compeleted:
            self.end_time = timezone.now()
            
    def get_absolute_url(self):
        return reverse("Pomodoro:index")



# "Theme" model is not related to anybody right now.
class Theme(models.Model):
    IMAGE = "IM"
    COLOR = "CO"
    STATUS_CHOICE = [(IMAGE, "Image"), (COLOR, "Color")]
    status = models.CharField(max_length=2, choices=STATUS_CHOICE, default=COLOR)
    theme_image = models.ImageField(upload_to="Images/uploads/%Y/%m/%d/")
    theme_color = models.CharField(max_length=10)
    theme_name = models.CharField(max_length=20)

    def __str__(self):
        return f"Theme-name: {self.theme_name}"

    # TODO: to complete below class visit https://adamj.eu/tech/2020/03/25/django-check-constraints-one-field-set/
    class Meta: ...


# "Notification" is in many-to-one relationship with "Timer".
# Why "many-to-one" ?
# Because, with same timer ongoing if user set "send_when = evey 5min" --> this means notification will be sent to user every 5min for the same timer.
class Notification(models.Model):
    timer = models.ForeignKey(Timer, on_delete=models.CASCADE)
    notification_text = models.CharField(
        max_length=100, default="Chutiye timer baj gaya"
    )
    # send_when : every or last (5min or ...)
    send_when = models.CharField(max_length=5)
    send_time = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"Notification: '{self.notification_text}' will be sent to you {self.send_when}: {self.send_time}min"


#  We dont need to connect blocksite with timer in many to one relationship.
class BlockSite(models.Model):
    site_url = models.URLField()
    quote = models.CharField(
        max_length=300,
        default="When I let go of what I am, I become what I might be. ~Lao Tzu",
    )

    def __str__(self):
        return f"Website: {self.site_url}"

Pomodoro/Pomodoro_App/forms.py
# I created this file so that I can understand how forms actually work in django, rather than using just those class-based-views.
# I coundnt understand anything in class-based-views.
from django.forms import ModelForm,formset_factory
from .models import *


class TimerForm(ModelForm):
    class Meta:
        model = Timer
        fields = "__all__"
        exclude = ["published_date"]

class SoundForm(ModelForm):
    class Meta:
        model = Sounds
        fields = "__all__"

class BlockSiteForm(ModelForm):
    class Meta:
        model = BlockSite
        fields = "__all__"


class TasksForm(ModelForm):
    class Meta:
        model = Tasks
        fields = ("task_text",)

    # didnt worked for me.
    # def __init__(self,*args,**kwargs):
    #     # here i just named pomodoro given by user as "selected_timer" and if there is no selected timer in kwargs dictionary then this will return "None".
    #     pomodoro = kwargs.pop("selected_timer",None)
    #     super().__init__(*args,**kwargs)
    #     self.fields["timer"].initial = pomodoro

Pomodoro/Pomodoro_App/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import Http404
from .models import *
from .forms import *
from django.core import serializers
from django.urls import reverse_lazy

# TODO: There's going to be 2 initial template, I need to build ---->
#      1) timer.html ---> displaying the data stored in databases.
#      2) settings.html ---> contains all the models which we have to take input from user.
#                 a) We need to wrap every model for which we need user input in one form.


# this is the view which provides the settings for the user to fill.
def settings(request):
    timer_form = TimerForm()
    sounds = Sounds.objects.all()
    blocksite_form = BlockSiteForm()

    context = {
        "timer_form": timer_form,
        "blocksite_form":blocksite_form,
        "sounds": sounds,
    }
    return render(request, "Pomodoro_App/settings.html", context)


# view for the actuall timer.
def pomodoro_timer(request):

    # default values(any random values) for variables.
    pomodoro_sound,breaks_sound = [1,1]

    try:
        # the topmost pomodoro is going to the timer.js
        pomodoro = Timer.objects.order_by("-published_date").first()
        if pomodoro == None:
            raise Http404
        serialized_data = serializers.serialize("json", [pomodoro])
    except Http404:
        return render(
            request,
            "Pomodoro_App\\settings.html",
            {"error_message": "No Pomodoro to start."},
        )
    

    # getting the input from the form which is in settings.html form.
    if request.method == "POST":
        time_form = TimerForm(request.POST)
        task_form = TasksForm(request.POST)
        sound = Sounds.objects.all().first()
        pomodoro_sound = request.POST.get('pomodoro_selected_audio',sound.get_sounds_url())
        breaks_sound = request.POST.get('breaks_selected_audio',sound.get_sounds_url())

        if time_form.is_valid():
            time_form.save()
        elif task_form.is_valid():
            # saving the pomodoro which is presently running before creating task.
            task = task_form.save(commit=False)
            task.timer = pomodoro
            task.save()
        else:
            # redirected to homepage
            return redirect("/")
        
    # If no input to the form is provided by the user, than below sound is gonna go off.
    sound = Sounds.objects.all().first()
    if pomodoro_sound == 1:
        pomodoro_sound = sound.get_sounds_url()
    if breaks_sound == 1:
        breaks_sound = sound.get_sounds_url()

    # below are the values that are being sent to the timer.html template to be rendered.
    latest_task_list = Tasks.objects.all() 

    if request.method == "GET":
        task_id = request.GET.get('task_id',False)
        checked = request.GET.get("checked",False)
        if task_id:
            task = Tasks.objects.get(id = task_id)
            if checked == '1':
                task.compeleted = True
            else:
                task.compeleted = False
            task.save()

    context = {
        "pomodoro": pomodoro,
        "serialized_data": serialized_data,
        "pomodoro_sound":pomodoro_sound,
        "break_sound":breaks_sound,
        "task_form":TasksForm(),
        "latest_task_list":latest_task_list,
    }

    return render(request, "Pomodoro_App/timer.html", context)

def deleteTask(request,task_id):
    task = get_object_or_404(Tasks,pk = task_id)
    task.delete()
    # redirect("Pomodoro:timer") ----> this will take me to the previous instance of the pomodoro_timer
    #  view.
    return redirect("Pomodoro:timer")

def wallClock(request):
    return render(request, "Pomodoro_App/clock.html")

Pomodoro/Pomodoro_App/templates/Pomodoro_App/clock.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Digital Wall Clock</title>
  <link rel="stylesheet" href="{% static 'Pomodoro_App/style_clock.css' %}">
</head>

<body>

  <div class="clock">
    <div class="clock__second"></div>
    <div class="clock__minute"></div>
    <div class="clock__hour"></div>
    <div class="clock__axis"></div>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
    <section class="clock__indicator"></section>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="{% static 'Pomodoro_App/js_clock.js' %}"></script>
</body>

</html>

Pomodoro/Pomodoro_App/templates/Pomodoro_App/settings.html
{% load static%}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Pomodoro Timer</title>
</head>

<body>
  <div class="center">
    <form method="post" id="timer_settings" action="{% url 'Pomodoro:timer'%}">
      {% csrf_token %} {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
      {% endif %}
      <h2>Timer ( minutes )</h2>
      {% for field in timer_form%} {% if field.name == "pomodoro"%}
      <div>
        <label for="Pomodoro">Pomodoro</label>
        {{ field }}
      </div>
      <br />
      {% elif field.name == "short_break"%}
      <div>
        <label for="short-break">Short Break</label>
        {{ field }}
      </div>
      <br />
      {% elif field.name == "long_break"%}
      <div>
        <label for="long-break">Long Break</label>
        {{ field }}
      </div>
      <br />
      {% elif field.name == "auto_start_breaks"%}
      <div>
        <label for="auto-start-breaks">Auto Start Breaks</label>
        {{field}}
      </div>
      <br />
      {% elif field.name == "auto_start_pomodoros"%}
      <div>
        <label for="auto-start-pomodoros">Auto Start Pomodoros</label>
        {{field}}
      </div>
      <br />
      {% elif field.name == "number_of_interval" %}
      <div>
        <label for="number-of-intervals">Long Break Intervals</label>
        {{ field }}
      </div>
      {% endif %} {% endfor %}
      <br />
      <hr />
      <div class="sounds-container">
        <h2>Sound</h2>
        <div class="pomodoro-sounds">
          <h3>Pomodoro Sound</h3>
          <select id="pomodoro-audio" name="pomodoro_selected_audio" onchange="playsound('pomodoro-audio')">
            <option value="none">--Select Audio--</option>
            {% for play in sounds %}
            <option value="{{play.sound.url}}">{{play.sound_name}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="break-sounds">
          <h3>Breaks Sound</h3>
          <select id="break-audio" name="breaks_selected_audio" onchange="playsound('break-audio')">
            <option value="none">--Select Audio--</option>
            {% for play in sounds %}
            <option value="{{play.sound.url}}">{{play.sound_name}}</option>
            {% endfor %}
          </select>
        </div>
        <audio id="player">
          <source id="sound-source" src="" type="audio/mp3" />
          Your browser doesnot support the audio tag.
        </audio>
      </div>
      <br />
      <br />
      <hr>
      <div class="button">
        <input type="submit" value="Save" />
        <input type="reset" value="Reset" />
      </div>
    </form>
  </div>
  <script src="{% static 'Pomodoro_App/settings.js' %}"></script>
</body>

</html>

Pomodoro/Pomodoro_App/templates/Pomodoro_App/timer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Focus on work</title>
  <link rel="stylesheet" href="{% static 'Pomodoro_App/styles.css' %}" />
</head>

<body>

  <section id="navbar-section">
    <!-- Image and text -->
    <nav id="navbar">
      <div class="div-brand">
        <a class="navbar-brand" href="{% url 'Pomodoro:timer'%}">
          <img src="{% static 'Pomodoro_App/images/bomb.svg'%}" width="40" height="40" class="company-icon" alt="">
        </a>
        <span id="brand-name">Based</span>
      </div>
      <div class="navbar-links">
        <a class="pomodoro-timer" href="{% url 'Pomodoro:timer'%}">Timer</a>
        <a class="timer-settings" href="{% url 'Pomodoro:settings'%}">Settings</a>
        <a class="wall-clock" href="{% url 'Pomodoro:clock'%}">Clock</a>
        <a class="wiki-learn" href="https://en.wikipedia.org/wiki/Pomodoro_Technique" target="_blank">
          <img src="{% static 'Pomodoro_App/images/up-right-arrow.png' %}" width="15" height="15"
            style="margin-right: 0.3rem;" alt="arrow to link">Learn</a>
      </div>
    </nav>
  </section>

  <main class="app">
    <div class="center">
      <div class="button-group" id="js-mode-buttons">
        <a data-mode="Pomodoro" class="button active pomodoro-button" type="button">
          Pomodoro
        </a>
        <a data-mode="shortBreak" class="button short-break-button" type="button">
          Short Break
        </a>
        <a data-mode="longBreak" class="button long-break-button" type="button">
          Long Break
        </a>
      </div>
      <div class="clock" id="js-clock">
        <span id="js-minutes">25</span>
        <span class="separator">:</span>
        <span id="js-seconds">00</span>
      </div>

      <!-- progress bar -->
      <div id="progress-bar">
        <progress id="js-progress-bar" value="0" max="100"></progress>
      </div>

      <div class="submit">
        <button class="submit-button" data-action="start" id="js-submit">
          Wind Up
        </button>
      </div>
    </div>


    <!-- task list -->
    <div id="tasks-model">
      <form method="post" action="{% url 'Pomodoro:timer'%}">
        {% csrf_token %}
        <h2 class="task-heading">Tasks</h2>
        {% for field in task_form %}
        {% if field.name == "task_text" %}
        {{ field}}
        {% endif %}
        {% endfor %}
        <button type="submit" class="add-task">Add</button>
      </form>
      <br>
      <br>
      <div class="task-list">
        {% for task in latest_task_list %}
        <!-- so, request.POST is getting the "value" from input tag not "name" -->
        <input type="checkbox" id="task-{{forloop.counter }}" name="task-list" data-taskid="{{task.id}}">
        <label for="task-{{forloop.counter }}"><strong>{{ task.task_text }}</strong></label>
        <a id="{{task.id}}" href="{% url 'Pomodoro:task-deletion' task.id %}" type="button">Delete</a>
        <br>
        {% endfor %}
      </div>
    </div>


    <div class="hidden">
      <audio id="pomodoro-audio" src="{{ pomodoro_sound }}"></audio>
      <audio id="break-audio" src="{{ break_sound }}"></audio>
    </div>
  </main>
  <script>
    // please put '{{ serialized_data| safe }}' this in single quotes not double quotes inside
    // the json.parse to avoid any errors.  
    var dataFromDatabase = JSON.parse('{{ serialized_data| safe }}');
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="{% static 'Pomodoro_App/index.js'%}"></script>
</body>

</html>